Controllers/AdministrationController.cs
using learnAspDotNetCore.Models;
using learnAspDotNetCore.Models.Types;
using learnAspDotNetCore.Tools;
using learnAspDotNetCore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace learnAspDotNetCore.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public readonly UserManager<AppUser> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager,
                                        UserManager<AppUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(AdministrationCreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole()
                {
                    Name = model.RoleName
                };
                IdentityResult result=await roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction(actionName: "Roles");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("",error.Description);
                }
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Roles()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id != null)
            {
                var role = await roleManager.FindByIdAsync(id);
                if (role != null)
                {
                    EditRoleViewModel model = new EditRoleViewModel()
                    {
                        Id=role.Id,
                        RoleName = role.Name,
                        Users=new List<string>()
                    };
                    foreach (AppUser user in userManager.Users)
                    {
                        if (await userManager.IsInRoleAsync(user, role.Name))
                        {
                            model.Users.Add(user.Email);
                        };
                    }
                    return View(model);
                }
                StatusResult result=new StatusResult() { 
                    Message=$"The Role as ID {id} cannot be found" 
                };
                return View("../Error/NotFound",result);
            }
            return RedirectToAction("Roles");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByIdAsync(model.Id);
                if (role == null)
                {
                    StatusResult status = new StatusResult()
                    {
                        Message = $"The Role as ID {model.Id} cannot be found"
                    };
                    return View("../Error/NotFound", status);
                }
                
                role.Name = model.RoleName;
                IdentityResult result =await this.roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Roles");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                
            }
            return View(model);
        }

        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> CheckingRoleName(EditRoleViewModel model)
        {
            var roleById = await roleManager.FindByIdAsync(model.Id);
            var roleByName = await roleManager.FindByNameAsync(model.RoleName);
            if (roleByName == null || roleById.Name==roleByName.Name) return Json(true);
            else return Json($"This role name ( {model.RoleName} ) is already exist.");
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersRole(string idRole)
        {
            if (string.IsNullOrEmpty(idRole))
            {
                return View("NotFound", $"The role must be exist and not empty in URL !.");
            }
            var role = await roleManager.FindByIdAsync(idRole);
            if (role == null )
            {
                return View("NotFound", $"The Role as ID {idRole} cannot be found");
            }

            List<EditUsersRoleViewModel> models=new List<EditUsersRoleViewModel>();
            foreach (AppUser user in userManager.Users)
            {
                EditUsersRoleViewModel model = new EditUsersRoleViewModel()
                {
                    UserId=user.Id,
                    UserName=user.UserName,
                    IsSelected=false
                };
                if (await userManager.IsInRoleAsync(user,role.Name))
                {
                    model.IsSelected=true;
                }
                models.Add(model);
            }
            ViewBag.IdRole=idRole;
            ViewBag.RoleName = role.Name;
            return View(models);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersRole(List<EditUsersRoleViewModel> models,string idRole)
        {
            if (string.IsNullOrEmpty(idRole))
            {
                return View("NotFound", $"The role must be exist and not empty in URL !.");
            }
            var role = await roleManager.FindByIdAsync(idRole);
            if (role == null)
            {
                return View("NotFound", $"The Role as ID {idRole} cannot be found");
            }
            foreach (var model in models)
            {
                IdentityResult result = null;
                AppUser user=await userManager.FindByIdAsync(model.UserId);
                if (await userManager.IsInRoleAsync(user,role.Name) && !model.IsSelected)
                {
                    result=await userManager.RemoveFromRoleAsync(user,role.Name);
                }
                else if (!(await userManager.IsInRoleAsync(user, role.Name)) && model.IsSelected)
                {
                    result=await userManager.AddToRoleAsync(user,role.Name);
                }
                if (result != null && !result.Succeeded) {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return RedirectToAction(nameof(Edit),new { id = idRole });
        }
    }
}

Controllers/EmployeeController.cs
using learnAspDotNetCore.Models;
using learnAspDotNetCore.Models.Repositories;
using learnAspDotNetCore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;

namespace learnAspDotNetCore.Controllers
{
    
    public class EmployeeController:Controller
    {
        private readonly ICompanyRepository<Employee> _employee;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EmployeeController(ICompanyRepository<Employee> employee, IWebHostEnvironment webHostEnvironment)
        {
            this._employee = employee;
            this.webHostEnvironment = webHostEnvironment;
        }

        [AllowAnonymous]
        public ViewResult Index()
        {
            IEnumerable<Employee> employees = _employee.GetAll();
            return View(employees);
        }

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id is null)
            {
                return RedirectToAction("Index");
            }
            Employee emp = _employee.Get(id ?? 1);
            if(emp == null){
                return View("NotFoundError",id);
            }
            return View(emp);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (model.Image!=null)
                {
                    string extFile = Path.GetExtension(model.Image.FileName);
                    if (extFile.ToLower() != ".png" && extFile.ToLower() != ".jpg")
                    {
                        ModelState.AddModelError("", "Invalid file format");
                        return View(model);
                    }
                    fileName = CreateImage(model);
                }
                Employee emp = new Employee() {
                    Email = model.Email,
                    Name = model.Name,
                    Departement = model.Departement,
                    ImageUrl = fileName
                };
                _employee.Add(emp);
                return RedirectToAction("Details", new { id = emp.Id });
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Employee employee=_employee.Get(id);
            if (employee == null)
            {
                return View("NotFoundError", id);
            }
            if (employee!=null)
            {
                EmployeeEditViewModel model = new EmployeeEditViewModel()
                {
                    Id = employee.Id,
                    imageOldPath = employee.ImageUrl,
                    Name= employee.Name,
                    Email = employee.Email,
                    Departement = employee.Departement,
                };
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(EmployeeEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Employee emp = _employee.Get(model.Id);

                emp.Email = model.Email;
                emp.Name = model.Name;
                emp.Departement = model.Departement;
                
                if (model.Image != null)
                {
                    string extFile = Path.GetExtension(model.Image.FileName);
                    if (extFile != ".png" && extFile != ".jpg")
                    {
                        ModelState.AddModelError("", "Invalid file format");
                        return View(model);
                    }
                    emp.ImageUrl = CreateImage(model);

                    // delete old image
                    string pathOldImage = Path.Combine(webHostEnvironment.WebRootPath, "Images", model.imageOldPath);
                    if (System.IO.File.Exists(pathOldImage))
                    {
                        System.IO.File.Delete(pathOldImage);
                    }
                }
                
                _employee.Update(emp);
                return RedirectToAction("Details", new { id = emp.Id });
            }
            return View(model);
        }


        // 
        private string CreateImage(EmployeeCreateViewModel model)
        {
            string fileName;
            string path = Path.Combine(webHostEnvironment.WebRootPath, "Images");
            fileName = Guid.NewGuid() + "_" + model.Image.FileName;
            path = Path.Combine(path, fileName);
            using (FileStream fs = new FileStream(path, FileMode.Create))
            {
                model.Image.CopyTo(fs);
            }

            return fileName;
        }
    }
}

Views/Shared/NotFound.cshtml
@model string
@{ ViewBag.Title = "Not Found";
}


<div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center ">
                <span class="display-1 d-block my-5">@ViewBag.Title</span>
                <div class="mb-4 lead">
                    <span class=text-danger>@Model</span>
                </div>
                <hr />
                <a asp-controller="Employee" asp-action="Index" class="btn btn-outline-dark">Back to Home Page</a>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> signInManager
@inject UserManager<AppUser> userManager

@{ 
}

<DOCTYPE html>
<html>
     <head>
        <title>@ViewBag.Title | Employees Management</title>
        <environment include="Development">
            <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
            <link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet">
        </environment>
        <environment include="Production,Staging">
            <link   href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" 
                    rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" 
                    crossorigin="anonymous"
                    asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
                    asp-fallback-test-class="sr-only"
                    asp-fallback-test-property="position"
                    asp-fallback-test-value="abslute"
                    asp-suppress-fallback-integrity="true">
            <link href="~/lib/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
        </environment>
        
        <link rel="icon" type="image/x-icon" href="/Images/logo.png" asp-append-version="true"  />
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="/">
                EMPLOYEE
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" asp-action="Index" asp-controller="Employee">Employees</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" asp-action="Create" asp-controller="Employee">Create Employee</a>
                </li>
                @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin")){
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Manage Roles</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-action="Roles" asp-controller="Administration">Roles</a></li>
                            <li><a class="dropdown-item" asp-action="Users" asp-controller="Account">Users</a></li>
                        </ul>
                    </li>
                }
            </ul>
                <ul class="navbar-nav d-flex">
                    @if(signInManager.IsSignedIn(User)){
                        string fullName = null;
                        AppUser user =await userManager.FindByEmailAsync(User.Identity.Name);
                        if (user!=null)
                        {
                            fullName = (user.FirstName??string.Empty).ToUpper() + " " + (user.LastName??string.Empty).ToLower();
                        }
                        if (fullName == null || fullName.Trim()=="") fullName = User.Identity.Name;

                        <li class="nav-item dropstart">
                            <button type="button" class="btn btn-outline-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                @fullName
                              </button>
                            <ul class="dropdown-menu">
                                <li>
                                    @using(Html.BeginForm("Edit","Account",FormMethod.Get)){
                                        <input type="text" name="Id" value="@user.Id" class="form-control" hidden/>
                                        <input type="submit" value="Edit Account" class="dropdown-item">
                                    }
                                </li>
                                <li><a class="dropdown-item" asp-action="Logout" asp-controller="Account">Logout</a></li>
                            </ul>
                        </li>
                    
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link btn-link" asp-action="Login" asp-controller="Account">Login</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link btn-link" asp-action="Register" asp-controller="Account">Register</a>
                        </li>  
                    }
                </ul>
            </div>
          </div>
        </nav>
        <div class="container">
             @RenderBody()
        </div>
        
        <environment include="Development">
            <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
            <script src="~/lib/jquery/jquery.js"></script>
            <script src="~/lib/jquery-validate/jquery.validate.js"></script>
            <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
            <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
            <script src="~/lib/jquery/jquery.min.js"></script>
            <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
            <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
            <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
        </environment>
        @RenderSection(name:"DTListUsers",required:false)
    </body>
</html>